# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'format_utility.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.formatter import formatter
import time

FILENAME = "empty"
FILETYPE = "empty"

class Ui_formatUtilityWindow(object):

    # Setting up UI
    def setupUi(self, formatUtilityWindow):
        
        formatUtilityWindow.setObjectName("formatUtilityWindow")
        formatUtilityWindow.resize(480, 450)
        formatUtilityWindow.setMaximumSize(QtCore.QSize(480, 450))
        #Logo
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        formatUtilityWindow.setWindowIcon(icon)
        #Styling Background
        formatUtilityWindow.setStyleSheet("background-color: rgb(0, 0, 34);")
        self.centralwidget = QtWidgets.QWidget(formatUtilityWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(20, 20, 440, 371))
        self.mainFrame.setStyleSheet("background-color: rgb(0, 32, 63);\n"
            "font: 9pt \"MS Shell Dlg 2\";\n"
            "color: rgb(255, 255, 255);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        
        #File Name Input
        self.fileLabel = QtWidgets.QLabel(self.mainFrame)
        self.fileLabel.setGeometry(QtCore.QRect(30, 80, 121, 16))
        self.fileLabel.setObjectName("fileLabel")
        self.fileInput = QtWidgets.QComboBox(self.mainFrame)
        self.fileInput.setGeometry(QtCore.QRect(180, 78, 171, 22))
        self.fileInput.setObjectName("fileInput")
        self.fileInput.addItem("")
        self.fileInput.addItem("")
        #File System Input
        self.nameLabel = QtWidgets.QLabel(self.mainFrame)
        self.nameLabel.setGeometry(QtCore.QRect(30, 30, 81, 20))
        self.nameLabel.setObjectName("nameLabel")
        self.nameInput = QtWidgets.QLineEdit(self.mainFrame)
        self.nameInput.setGeometry(QtCore.QRect(180, 30, 171, 22))
        self.nameInput.setObjectName("nameInput")
        #Table to display differences between file systems
        self.descTable = QtWidgets.QTableWidget(self.mainFrame)
        self.descTable.setGeometry(QtCore.QRect(30, 130, 385, 105))
        self.descTable.setStyleSheet("background-color: rgb(170, 170, 170);\n"
            "gridline-color: rgb(0, 56, 0);\n"
            "color: rgb(68, 68, 68);\n"
            "\n"
            "")
        self.descTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.descTable.setObjectName("descTable")
        self.descTable.setColumnCount(3)
        self.descTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.descTable.setItem(1, 2, item)
        
        #Start scan button
        self.startButton = QtWidgets.QPushButton(self.mainFrame, clicked = lambda: self.startFormatting())
        self.startButton.setGeometry(QtCore.QRect(320, 270, 97, 28))
        self.startButton.setStyleSheet("QPushButton{\n"
            "    font: 75 9pt \"MS Shell Dlg 2\";\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(173, 240, 209);\n"
            "    border-radius: 5px\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: rgb(138, 237, 246);\n"
            "}")
        self.startButton.setObjectName("startButton")
        #Progress bar
        self.formatProgress = QtWidgets.QProgressBar(self.mainFrame)
        self.formatProgress.setGeometry(QtCore.QRect(30, 320, 391, 23))
        self.formatProgress.setProperty("value", 0)
        self.formatProgress.setOrientation(QtCore.Qt.Horizontal)
        self.formatProgress.setInvertedAppearance(False)
        self.formatProgress.setObjectName("formatProgress")
        #Display data loss warning
        self.warnLabel = QtWidgets.QLabel(self.mainFrame)
        self.warnLabel.setGeometry(QtCore.QRect(160, 240, 261, 16))
        self.warnLabel.setStyleSheet("font: italic 6pt \"Arial\";\n"
            "color: rgb(180, 180, 180);")
        self.warnLabel.setObjectName("warnLabel")
        #Exit Utility button
        self.exitButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.closer())
        self.exitButton.setGeometry(QtCore.QRect(360, 406, 100, 28))
        self.exitButton.setStyleSheet("QPushButton{\n"
            "    font: 75 9pt \"MS Shell Dlg 2\";\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(173, 240, 209);\n"
            "    border-radius: 5px\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: rgb(138, 237, 246);\n"
            "}")
        self.exitButton.setObjectName("exitButton")

        formatUtilityWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(formatUtilityWindow)
        QtCore.QMetaObject.connectSlotsByName(formatUtilityWindow)

    def startFormatting(self):
        FILENAME = self.nameInput.displayText()
        FILETYPE = self.fileInput.currentText()
        self.nameInput.setText(FILENAME)
        print("Formatting started: \nFilename - " + FILENAME + "\nFile System - " + FILETYPE)
        self.mainFrame.setStyleSheet("background-color: rgb(89, 98, 127);\n"
            "color: rgb(255, 255, 255);")
        self.mainFrame.setDisabled(True)
        #self.progressLoad()
        i = 1
        if FILETYPE == "NTFS":
            i = 1
        else:
            i = 0
        formatter().rewrite_script(i, FILENAME)

    def progressLoad(self):
        for i in range(101):
            time.sleep(0.07)
            self.formatProgress.setValue(i)

    def closer(self):
        import sys
        sys.exit()

    def retranslateUi(self, formatUtilityWindow):
        _translate = QtCore.QCoreApplication.translate
        formatUtilityWindow.setWindowTitle(_translate("formatUtilityWindow", "Format Utility"))
        self.fileLabel.setText(_translate("formatUtilityWindow", "File System Type:"))
        self.fileInput.setItemText(0, _translate("formatUtilityWindow", "NTFS"))
        self.fileInput.setItemText(1, _translate("formatUtilityWindow", "FAT32"))
        self.nameLabel.setText(_translate("formatUtilityWindow", "New Name: "))
        item = self.descTable.horizontalHeaderItem(0)
        item.setText(_translate("formatUtilityWindow", "File System"))
        item = self.descTable.horizontalHeaderItem(1)
        item.setText(_translate("formatUtilityWindow", "Compatability"))
        item = self.descTable.horizontalHeaderItem(2)
        item.setText(_translate("formatUtilityWindow", "Size"))
        __sortingEnabled = self.descTable.isSortingEnabled()
        self.descTable.setSortingEnabled(False)
        item = self.descTable.item(0, 0)
        item.setText(_translate("formatUtilityWindow", "NTFS"))
        item = self.descTable.item(0, 1)
        item.setText(_translate("formatUtilityWindow", "Windows, Linux, MacOS(read-only)"))
        item = self.descTable.item(0, 2)
        item.setText(_translate("formatUtilityWindow", "1 KB - 16 EiB"))
        item = self.descTable.item(1, 0)
        item.setText(_translate("formatUtilityWindow", "FAT32"))
        item = self.descTable.item(1, 1)
        item.setText(_translate("formatUtilityWindow", "Windows, Linux, MacOS"))
        item = self.descTable.item(1, 2)
        item.setText(_translate("formatUtilityWindow", "upto 32GB"))
        self.descTable.setSortingEnabled(__sortingEnabled)
        self.startButton.setText(_translate("formatUtilityWindow", "START"))
        self.warnLabel.setText(_translate("formatUtilityWindow", "*Warning: This process will wipe all your data on drive"))
        self.exitButton.setText(_translate("formatUtilityWindow", "EXIT"))
