# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'host_utility.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from src.hosting import hosting
import qrcode




SETURL = "URL: http://192.168.1.40:4747"


class Ui_hostUtilityWindow(object):
    def setupUi(self, hostUtilityWindow):

        hostUtilityWindow.setObjectName("hostUtilityWindow")
        hostUtilityWindow.resize(880, 480)
        hostUtilityWindow.setMaximumSize(QtCore.QSize(880, 480))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        hostUtilityWindow.setWindowIcon(icon)
        hostUtilityWindow.setStyleSheet("background-color: rgb(0, 0, 34);\n"
            "")
        self.centralwidget = QtWidgets.QWidget(hostUtilityWindow)
        self.centralwidget.setObjectName("centralwidget")

        #Group box for links to access files
        self.linksBox = QtWidgets.QGroupBox(self.centralwidget)
        self.linksBox.setGeometry(QtCore.QRect(20, 20, 321, 430))
        self.linksBox.setStyleSheet("background-color: rgb(0, 32, 63);\n"
            "font: 9pt \"MS Shell Dlg 2\";\n"
            "color: rgb(255, 255, 255);")
        self.linksBox.setObjectName("linksBox")

        self.urlLabel = QtWidgets.QLabel(self.linksBox)
        self.urlLabel.setGeometry(QtCore.QRect(20, 40, 221, 16))
        self.urlLabel.setObjectName("urlLabel")
        self.scanLabel = QtWidgets.QLabel(self.linksBox)
        self.scanLabel.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.scanLabel.setObjectName("scanLabel")
        #QR code to scan and access
        self.QRImage = QtWidgets.QLabel(self.linksBox)
        self.QRImage.setGeometry(QtCore.QRect(20, 120, 280, 280))
        self.QRImage.setText("")
        qr = qrcode.QRCode(
            version=3,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        dataqr = SETURL
        dataqr = dataqr.replace("URL: ","")
        print(dataqr)
        qr.add_data(dataqr)
        img = qr.make_image(back_color=(173, 240, 209))
        type(img)
        img.save("icons/qr.png")
        self.QRImage.setPixmap(QtGui.QPixmap("icons/qr.png"))
        self.QRImage.setScaledContents(True)
        self.QRImage.setObjectName("QRImage")


        #Access Logs
        self.logsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.logsBox.setGeometry(QtCore.QRect(360, 20, 501, 391))
        self.logsBox.setStyleSheet("background-color: rgb(0, 32, 63);\n"
            "font: 9pt \"MS Shell Dlg 2\";\n"
            "color: rgb(255, 255, 255);")
        self.logsBox.setObjectName("logsBox")

        self.logsBox.setObjectName("logsBox")
        self.logsLabel = QtWidgets.QLabel(self.logsBox)
        self.logsLabel.setGeometry(QtCore.QRect(20, 30, 461, 331))
        self.logsLabel.setStyleSheet("font: 75 10pt \"Courier\";\n"
                                     "background-color: rgb(40, 44, 52);\n"
                                     "color: rgb(255, 0, 0);")
        self.logsLabel.setText("")
        self.logsLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.logsLabel.setWordWrap(True)
        self.logsLabel.setObjectName("logsLabel")

        #Exit Utility
        self.exitButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.closer())
        self.exitButton.setGeometry(QtCore.QRect(760, 420, 93, 28))
        self.exitButton.setStyleSheet("QPushButton{\n"
            "    font: 75 9pt \"MS Shell Dlg 2\";\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(173, 240, 209);\n"
            "    border-radius: 5px\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: rgb(138, 237, 246);\n"
            "}")
        self.exitButton.setObjectName("exitButton")

        # Start & Stop Button
        self.startButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.hostbutton(1))
        self.startButton.setGeometry(QtCore.QRect(360, 420, 93, 28))
        self.startButton.setStyleSheet("QPushButton{\n"
                                      "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                      "    color: rgb(0, 0, 0);\n"
                                      "    background-color: rgb(173, 240, 209);\n"
                                      "    border-radius: 5px\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(138, 237, 246);\n"
                                      "}")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.hostbutton(0))
        self.stopButton.setGeometry(QtCore.QRect(360, 420, 93, 28))
        self.stopButton.setStyleSheet("QPushButton{\n"
                                       "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "    background-color: rgb(173, 240, 209);\n"
                                       "    border-radius: 5px\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(138, 237, 246);\n"
                                       "}")
        self.stopButton.setObjectName("stopButton")
        self.stopButton.hide()

        hostUtilityWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(hostUtilityWindow)
        self.statusbar.setObjectName("statusbar")
        hostUtilityWindow.setStatusBar(self.statusbar)

        self.retranslateUi(hostUtilityWindow)
        QtCore.QMetaObject.connectSlotsByName(hostUtilityWindow)

    def closer(self):
        import sys

        print("Server stopped")
        sys.exit()


    def hostbutton(self, i):
        self.worker = WorkerThread()
        if i == 1:
            self.startButton.hide()
            self.stopButton.show()
            self.worker.start()
        else:
            hosting().stopHost()
            self.worker.exit()
            self.stopButton.setDisabled(True)
            print("Server stopping")
            with open('E:\logs.txt', 'r') as file:
                data = file.read()
                self.logsLabel.setText(data)



    def retranslateUi(self, hostUtilityWindow):
        _translate = QtCore.QCoreApplication.translate
        hostUtilityWindow.setWindowTitle(_translate("hostUtilityWindow", "Hosting Utility"))
        self.linksBox.setTitle(_translate("hostUtilityWindow", "File Link"))
        self.urlLabel.setText(_translate("hostUtilityWindow", SETURL))
        self.scanLabel.setText(_translate("hostUtilityWindow", "OR Scan QR -"))
        self.logsBox.setTitle(_translate("hostUtilityWindow", "Logs"))
        self.exitButton.setText(_translate("hostUtilityWindow", "EXIT"))
        self.startButton.setText(_translate("hostUtilityWindow", "START"))
        self.stopButton.setText(_translate("hostUtilityWindow", "STOP"))


class WorkerThread(QThread):
    def run(self):
        print("Files hosted")
        sp = hosting().hostFiles()
        print(sp.type())


